markdown: kramdown
highlighter: rouge

title: BiasedBit
url: http://biasedbit.com
author: Bruno de Carvalho
email: bruno@biasedbit.com
twitter_username: biasedbit
github_username: biasedbit
linkedin_username: biasedbit
